<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $basePath = storage_path('app/templates');

        $templates = [
            [
                'name' => 'Booking & Reservation Platform',
                'slug' => 'booking-platform',
                'category' => 'operations',
                'description' => 'Appointment scheduling with calendar, reminders, and online booking. Perfect for salons, clinics, studios, sports courts.',
                'icon' => 'calendar_month',
                'complexity' => 'medium',
                'models_count' => 8,
                'tags' => ['Scheduling', 'Services'],
                'available' => true,
            ],
            [
                'name' => 'Project Management Tool',
                'slug' => 'project-management',
                'category' => 'operations',
                'description' => 'Kanban boards, task assignments, time tracking, and team collaboration for agencies and dev teams.',
                'icon' => 'task_alt',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Kanban', 'Tasks'],
                'available' => true,
            ],
            [
                'name' => 'Inventory & Stock Management',
                'slug' => 'inventory-management',
                'category' => 'operations',
                'description' => 'Real-time stock tracking across multiple locations with low-stock alerts and SKU management.',
                'icon' => 'inventory_2',
                'complexity' => 'medium',
                'models_count' => 9,
                'tags' => ['Logistics', 'Retail'],
                'available' => false,
            ],
            [
                'name' => 'Field Service Management',
                'slug' => 'field-service',
                'category' => 'operations',
                'description' => 'Work orders, technician dispatch, parts tracking, and client portal for repair and maintenance businesses.',
                'icon' => 'engineering',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Dispatch', 'Work Orders'],
                'available' => false,
            ],
            [
                'name' => 'Fleet & Vehicle Management',
                'slug' => 'fleet-management',
                'category' => 'operations',
                'description' => 'Vehicle tracking, maintenance schedules, fuel logging, and driver management for logistics companies.',
                'icon' => 'local_shipping',
                'complexity' => 'medium',
                'models_count' => 9,
                'tags' => ['Vehicles', 'Logistics'],
                'available' => false,
            ],
            [
                'name' => 'CRM',
                'slug' => 'crm',
                'category' => 'sales',
                'description' => 'Customer relationship management with pipeline tracking, interaction history, and lead scoring.',
                'icon' => 'bolt',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Pipeline', 'SaaS'],
                'available' => true,
            ],
            [
                'name' => 'Invoice & Billing Platform',
                'slug' => 'invoice-billing',
                'category' => 'sales',
                'description' => 'Invoice generation, recurring billing, expense tracking, and financial dashboards for freelancers and agencies.',
                'icon' => 'receipt_long',
                'complexity' => 'medium',
                'models_count' => 10,
                'tags' => ['Invoicing', 'Finance'],
                'available' => true,
            ],
            [
                'name' => 'E-commerce / Online Store',
                'slug' => 'ecommerce',
                'category' => 'sales',
                'description' => 'Product catalog with variants, shopping cart, checkout, order management, and Stripe payments.',
                'icon' => 'shopping_cart',
                'complexity' => 'high',
                'models_count' => 13,
                'tags' => ['Store', 'Payments'],
                'available' => false,
            ],
            [
                'name' => 'Subscription & Membership Platform',
                'slug' => 'subscription-platform',
                'category' => 'sales',
                'description' => 'Plan management, recurring billing, usage tracking, and member portal for SaaS and membership businesses.',
                'icon' => 'card_membership',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Billing', 'Members'],
                'available' => false,
            ],
            [
                'name' => 'Content Management / Blog',
                'slug' => 'cms-blog',
                'category' => 'content',
                'description' => 'Multi-author blog with rich editor, SEO, categories, revision history, and media library.',
                'icon' => 'article',
                'complexity' => 'medium',
                'models_count' => 11,
                'tags' => ['Publishing', 'SEO'],
                'available' => false,
            ],
            [
                'name' => 'Newsletter & Email Marketing',
                'slug' => 'newsletter',
                'category' => 'content',
                'description' => 'Subscriber management, campaign builder, email templates, and open/click analytics.',
                'icon' => 'mail',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Email', 'Marketing'],
                'available' => false,
            ],
            [
                'name' => 'Helpdesk & Support Tickets',
                'slug' => 'helpdesk',
                'category' => 'content',
                'description' => 'Ticket management with assignment, SLA tracking, canned responses, and customer portal.',
                'icon' => 'support_agent',
                'complexity' => 'medium-high',
                'models_count' => 11,
                'tags' => ['Support', 'Tickets'],
                'available' => false,
            ],
            [
                'name' => 'Two-Sided Marketplace',
                'slug' => 'marketplace',
                'category' => 'marketplace',
                'description' => 'Seller profiles, listings, messaging, order flow, reviews, and split payments for service or product marketplaces.',
                'icon' => 'storefront',
                'complexity' => 'high',
                'models_count' => 12,
                'tags' => ['Listings', 'Payments'],
                'available' => false,
            ],
            [
                'name' => 'Job Board / Recruitment',
                'slug' => 'job-board',
                'category' => 'marketplace',
                'description' => 'Job posting, application flow, applicant tracking, company profiles, and email alerts.',
                'icon' => 'work',
                'complexity' => 'medium',
                'models_count' => 10,
                'tags' => ['Jobs', 'Hiring'],
                'available' => false,
            ],
            [
                'name' => 'Directory & Listing Platform',
                'slug' => 'directory',
                'category' => 'marketplace',
                'description' => 'Categorized listings with search, reviews, business claiming, and promoted listings.',
                'icon' => 'place',
                'complexity' => 'medium',
                'models_count' => 11,
                'tags' => ['Listings', 'Search'],
                'available' => false,
            ],
            [
                'name' => 'LMS (Learning Management)',
                'slug' => 'lms',
                'category' => 'education',
                'description' => 'Course builder, video lessons, progress tracking, quizzes, certificates, and instructor dashboards.',
                'icon' => 'school',
                'complexity' => 'high',
                'models_count' => 12,
                'tags' => ['Courses', 'Learning'],
                'available' => false,
            ],
            [
                'name' => 'School / Academy Management',
                'slug' => 'school-management',
                'category' => 'education',
                'description' => 'Student enrollment, class scheduling, attendance, payment plans, and progress reports.',
                'icon' => 'menu_book',
                'complexity' => 'medium-high',
                'models_count' => 12,
                'tags' => ['Students', 'Classes'],
                'available' => false,
            ],
            [
                'name' => 'Patient / Client Records',
                'slug' => 'patient-records',
                'category' => 'health',
                'description' => 'Patient profiles with medical history, treatment records, document uploads, and GDPR compliance.',
                'icon' => 'health_and_safety',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['EHR', 'Compliance'],
                'available' => false,
            ],
            [
                'name' => 'Fitness & Wellness Platform',
                'slug' => 'fitness-wellness',
                'category' => 'health',
                'description' => 'Training plans, exercise library, workout logging, meal planning, and client portal.',
                'icon' => 'fitness_center',
                'complexity' => 'medium',
                'models_count' => 12,
                'tags' => ['Training', 'Health'],
                'available' => false,
            ],
            [
                'name' => 'Restaurant & Café Management',
                'slug' => 'restaurant-management',
                'category' => 'hospitality',
                'description' => 'Digital menu with QR codes, table management, waiter calls, and multi-language support.',
                'icon' => 'restaurant',
                'complexity' => 'medium',
                'models_count' => 11,
                'tags' => ['Menu', 'QR Code'],
                'available' => true,
            ],
            [
                'name' => 'Property / Rental Management',
                'slug' => 'property-rental',
                'category' => 'hospitality',
                'description' => 'Property listings, availability calendar, booking management, seasonal pricing, and guest communication.',
                'icon' => 'home_work',
                'complexity' => 'high',
                'models_count' => 12,
                'tags' => ['Rentals', 'Booking'],
                'available' => false,
            ],
            [
                'name' => 'Analytics / Dashboard Builder',
                'slug' => 'analytics-dashboard',
                'category' => 'analytics',
                'description' => 'Drag-drop dashboards, multiple chart types, data source connections, and scheduled reports.',
                'icon' => 'bar_chart',
                'complexity' => 'high',
                'models_count' => 10,
                'tags' => ['Charts', 'BI'],
                'available' => false,
            ],
            [
                'name' => 'Monitoring & Alerting',
                'slug' => 'monitoring-alerting',
                'category' => 'analytics',
                'description' => 'Uptime monitors, incident management, public status pages, and multi-channel alerts.',
                'icon' => 'monitor_heart',
                'complexity' => 'medium-high',
                'models_count' => 10,
                'tags' => ['Uptime', 'Alerts'],
                'available' => false,
            ],
            [
                'name' => 'Event Management Platform',
                'slug' => 'event-management',
                'category' => 'specialized',
                'description' => 'Event creation, ticket sales, attendee management, speaker profiles, and QR check-in.',
                'icon' => 'event',
                'complexity' => 'medium-high',
                'models_count' => 12,
                'tags' => ['Events', 'Tickets'],
                'available' => false,
            ],
            [
                'name' => 'API-as-a-Service',
                'slug' => 'api-service',
                'category' => 'specialized',
                'description' => 'API key management, rate limiting, usage metering, subscription billing, and auto-generated docs.',
                'icon' => 'terminal',
                'complexity' => 'medium-high',
                'models_count' => 11,
                'tags' => ['Developer', 'Backend'],
                'available' => false,
            ],
        ];

        foreach ($templates as $template) {
            $dir = $basePath . '/' . $template['slug'];
            if (!is_dir($dir)) {
                mkdir($dir, 0755, true);
            }

            $metaFile = $dir . '/template.json';
            // Don't overwrite existing template.json (preserves manually created ones)
            if (!file_exists($metaFile)) {
                file_put_contents($metaFile, json_encode($template, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
            }
        }
    }
}
