<?php

namespace App\Services;

use App\Models\Project;
use App\Models\User;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class GitHubService
{
    private const API_BASE = 'https://api.github.com';

    public function export(User $user, Project $project, string $repoName): array
    {
        $token = $user->github_token;

        // Step 1: Create repo
        $repoResponse = $this->githubRequest($token, 'POST', '/user/repos', [
            'name' => $repoName,
            'description' => $project->description ?? 'Generated by Draplo',
            'private' => true,
            'auto_init' => false,
        ]);

        $repoFullName = $repoResponse['full_name'];
        $repoUrl = $repoResponse['html_url'];

        // Step 2: Create blobs for each file
        $blobs = [];
        foreach ($project->generation_output as $file) {
            $blobResponse = $this->githubRequest($token, 'POST', "/repos/{$repoFullName}/git/blobs", [
                'content' => $file['content'],
                'encoding' => 'utf-8',
            ]);
            $blobs[] = [
                'path' => $file['path'],
                'mode' => '100644',
                'type' => 'blob',
                'sha' => $blobResponse['sha'],
            ];
        }

        // Step 3: Create tree
        $treeResponse = $this->githubRequest($token, 'POST', "/repos/{$repoFullName}/git/trees", [
            'tree' => $blobs,
        ]);

        // Step 4: Create commit
        $commitResponse = $this->githubRequest($token, 'POST', "/repos/{$repoFullName}/git/commits", [
            'message' => 'Initial scaffold generated by Draplo',
            'tree' => $treeResponse['sha'],
        ]);

        // Step 5: Create ref (main branch)
        $this->githubRequest($token, 'POST', "/repos/{$repoFullName}/git/refs", [
            'ref' => 'refs/heads/main',
            'sha' => $commitResponse['sha'],
        ]);

        return [
            'repo_url' => $repoUrl,
            'repo_name' => $repoFullName,
        ];
    }

    private function githubRequest(string $token, string $method, string $path, array $data = [], int $retries = 0): array
    {
        $response = Http::timeout(30)
            ->connectTimeout(10)
            ->withHeaders([
                'Authorization' => "Bearer {$token}",
                'Accept' => 'application/vnd.github.v3+json',
            ])
            ->{strtolower($method)}(self::API_BASE . $path, $data);

        if (in_array($response->status(), [403, 429]) && $retries < 3) {
            $delay = pow(2, $retries);
            sleep($delay);
            Log::warning("GitHub API rate limit, retrying in {$delay}s", ['path' => $path, 'retry' => $retries + 1]);
            return $this->githubRequest($token, $method, $path, $data, $retries + 1);
        }

        if ($response->status() === 401) {
            throw new \RuntimeException('GitHub token expired or revoked. Please re-login via GitHub.');
        }

        if ($response->status() === 422) {
            $message = $response->json('message') ?? 'Validation failed';
            if (str_contains($message, 'name already exists')) {
                throw new \RuntimeException('Repository name already exists on your GitHub account.');
            }
            throw new \RuntimeException("GitHub API error: {$message}");
        }

        if (!$response->successful()) {
            throw new \RuntimeException("GitHub API error ({$response->status()}): " . $response->body());
        }

        return $response->json();
    }
}
